% ---------------------------------------- %
%   Plots results for geometric mean
%   generated by main.m
% ---------------------------------------- %

figure(1)
%legendStr = {'Zhang','FWE','FWR','CG','SD','BB','LBFGS','MM'};
legendStr = {'Zhang','FWE','FWR','BB','LBFGS','MM'};
loglog(time_zhang,out_zhang,'LineWidth',3,'Color',[0, 0.4470, 0.7410])
hold all
loglog(time_E,output_E,'--','LineWidth',3,'Color',[0.8500, 0.3250, 0.0980]);
loglog(time_R,output_R,'--','LineWidth',3,'Color',[0.6350, 0.0780, 0.1840]	)
%loglog(man1.tm,man1.it,'LineWidth',3,'Color',[0.4940, 0.1840, 0.5560])
%loglog(man2.tm,man2.it,'LineWidth',3,'Color',[0, 0.75, 0.75])
loglog(man4.tm,man4.it,'LineWidth',3,'Color',[0.75, 0.75, 0])
loglog(T_lb,out_lb,'LineWidth',3,'Color',[0.25, 0.25, 0.25])
loglog(time_mm,out_mm,'LineWidth',3,'Color',[0, 0.5, 0])
legend(legendStr);
xlabel('time (s)');
ylabel('loss function');
set(gca,'linewidth',2);
set(gca,'fontsize', 20);
ax = gca;
ax.FontSize = 16; 
title('Performance');

figure(2)
%legendStr = {'Zhang','FWE','FWR','CG','SD','BB','LBFGS','MM'};
legendStr = {'Zhang','FWE','FWR','BB','LBFGS','MM'};
loglog(1:length(out_zhang),out_zhang,'LineWidth',3,'Color',[0, 0.4470, 0.7410])
hold all
loglog(1:length(output_E),output_E,'--','LineWidth',3,'Color',[0.8500, 0.3250, 0.0980]);
loglog(1:length(output_R),output_R,'--','LineWidth',3,'Color',[0.6350, 0.0780, 0.1840]	)
%loglog(1:length(man1.it),man1.it,'LineWidth',3,'Color',[0.4940, 0.1840, 0.5560])
%loglog(1:length(man2.it),man2.it,'LineWidth',3,'Color',[0, 0.75, 0.75])
loglog(1:length(man4.it),man4.it,'LineWidth',3,'Color',[0.75, 0.75, 0])
loglog(1:length(out_lb),out_lb,'LineWidth',3,'Color',[0.25, 0.25, 0.25])
loglog(1:length(out_mm),out_mm,'LineWidth',3,'Color',[0, 0.5, 0])
legend(legendStr);
xlabel('#iterations');
ylabel('loss function');
set(gca,'linewidth',2);
set(gca,'fontsize', 20);
ax = gca;
ax.FontSize = 16; 
title('Performance');

figure(3)
legendStr = {'FWE','FWR','LBFGS'};
loglog(1:length(output_E),grad_E,'--','LineWidth',3,'Color',[0.8500, 0.3250, 0.0980])
hold all
loglog(1:length(output_R),grad_R,'--','LineWidth',3,'Color',[0.6350, 0.0780, 0.1840])
loglog(1:length(out_lb),G_lb,'LineWidth',3,'Color',[0.25, 0.25, 0.25])
legend(legendStr);
xlabel('#iterations');
ylabel('Gradient norm');
set(gca,'linewidth',2);
set(gca,'fontsize', 20);
ax = gca;
ax.FontSize = 16; 
title('Performance');
